format_version: 10


pipelines:
  tests:
    group: service
    materials:
      saving:
        scm: ee188c0c-f398-4b41-960e-10901377a4c0
    lock_behavior: none
    environment_variables:
      GOPRIVATE: github.com/kkp-dfs/*
      GOPROXY: https://nexus.mydime.tech/repository/go-proxy,direct
      GH_ACCESS_TOKEN: '{{SECRET:[vault-gocd][gh_access_token]}}'
    stages:
      - unit_test:
          clean_workspace: true
          jobs:
            unit_test:
              elastic_profile_id: golang-agent
              tasks:
                - script: |
                    cat <<EOF > .netrc
                    machine github.com
                      login $GH_ACCESS_TOKEN
                      password x-oauth-basic
                    EOF
                    chmod 600 .netrc
                    cp .netrc $HOME/.netrc
                - script: |
                    export PATH=$HOME/go/bin:$(go env GOPATH)/bin:/go/bin:$PATH
                    touch $HOME/.ack-ginkgo-rc
                    make tidy
                    make tools-install
                    make unit-test
                    make generate-unitcoverage
