format_version: 10

common:
  netrc: &netrc |
    cat <<EOF > .netrc
    machine github.com
      login $GH_ACCESS_TOKEN
      password x-oauth-basic
    EOF
    chmod 600 .netrc
    cp .netrc $HOME/.netrc
  deps_setup: &deps_setup |
    touch $HOME/.ack-ginkgo-rc
    make tidy
    make tools-install

pipelines:
  parameters:
    git_repo: dime-saving-account.git
  tests:
    group: service
    materials:
      saving:
        git: https://github.com/kkp-dfs/#{git_repo}
        branch: main
        username: '{{SECRET:[vault-gocd][gh_access_toke]}}'
        password: x-oauth-basic
    lock_behavior: none
    environment_variables:
      GOPRIVATE: github.com/kkp-dfs/*
      GOPROXY: https://nexus.mydime.tech/repository/go-proxy,direct
      GH_ACCESS_TOKEN: '{{SECRET:[vault-gocd][gh_access_token]}}'
    stages:
      - unit_test:
          clean_workspace: true
          jobs:
            lint:
              elastic_profile_id: golang-agent
              tasks:
                - script: *netrc
                - script: *deps_setup
                - script: golangci-lint run --timeout 2m0s -E gosec ./...
                - script: golangci-lint run --timeout 2m0s -E gocyclo ./...

            unit_test:
              elastic_profile_id: golang-agent
              artifacts:
                - test:
                    source: coverage
                    destination: reports
              tasks:
                - script: *netrc
                - script: *deps_setup
                - script: |
                    export PATH=$HOME/go/bin:$(go env GOPATH)/bin:/go/bin:$PATH
                    make unit-test
                    make generate-unitcoverage
                - script: genhtml --rc lcov_branch_coverage=1 -o coverage unitcoverage.lcov
